#!/bin/sh
# -------
# File:        packet-tracer-installer-gui
# Description: simple packet tracer installation assistant
#              using zenity
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

remove_garbage(){
	if [ "$TMPDIR" ] && [ -d "$TMPDIR" ] ; then
		rm -fr "$TMPDIR"
	fi
}

die(){
	zenity --title "Error"  --error --text="$1"
	remove_garbage
	exit 1
}

progress(){
	zenity --no-cancel --auto-close --progress --pulsate --text="$1"
}



end_message(){
	zenity --info --title="Instalación de Packet Tracer" --text="Instalación finalizada con éxito\nPor favor cierre e inicie de nuevo la sesión para ejecutar Packet Tracer" 2>/dev/null
	remove_garbage
}

untar(){
	FILE="$1"
	DIR="$2"
	tar -C "$DIR" -xzf "$FILE" || rc=$?
}

get_newdir(){
	DIR="$1"
	rc=0
	NEW_DIR=""
	for f in eula.txt install; do
		F="$(find "$DIR" -name "$f" 2>/dev/null)"
		[ "$F" ] || rc=1
	done
	if [ $rc -eq 0 ] ; then
		NEW_DIR="$(dirname "$F")"
	fi
	echo "$NEW_DIR"
}

select_file(){
	rc=0
	f="$(zenity --title="Seleccione el fichero comprimido de Packet Tracer" --file-selection --file-filter='Packet Tracer tarball (tar.gz,tgz) | *.tar.gz *.tgz' 2>/dev/null)" || rc=$?
	if [ $rc -eq 0 ] && [ -r "$f" ] && file "$f" |grep -q "gzip" ; then
		echo "$f"
	fi
}

do_start(){
	zenity --question --title="Instalación de Packet Tracer" --text "Este programa necesita que usted haya descargado previamente\nel fichero comprimido de Packet Tracer utilizando una cuenta válida.\n\nA continuación se le pedirá que sellecione la ruta completa del fichero descargado.\n\n¿Está seguro de querer continuar?" 2>/dev/null || return 1
	return 0
}

show_eula(){
	zenity --width=700 --height=600 --title="Cisco Packet Tracer Software License Agreement" --text-info --filename="$1" 2>/dev/null || return 1
	return 0
}

run_wrapper(){
	rc=0
	DIR="$1"
	/usr/share/packet-tracer-installer/packet-tracer-wrapper "$DIR" || rc=$?
	return $rc
}

fix_desktop(){
	LOCAL_TARGET="/usr/local/bin/packettracer"
	rm -f "$LOCAL_TARGET"
	cp -a /usr/share/packet-tracer-installer/packettracer "$LOCAL_TARGET"
	DFILE="$(rgrep -li "packet tracer" /usr/share/applications/ |grep -v "packet-tracer-installer.desktop")"
	if [ "$DFILE" ] && [ -x /usr/local/bin/packettracer ] ; then
		sed -i -e "/^Exec=/s%=.*$%=/usr/local/bin/packettracer%" "$DFILE" || true
	fi
		
}

# main

[ $(id -u) -eq 0 ] || die "root privileges required"
rc=0
do_start || die "Cancelado por el usuario"
TARBALL="$(select_file)"
[ "$TARBALL" ] || die "No se ha seleccionado un fichero válido"
TMPDIR="$(mktemp -d)"
untar "$TARBALL" "$TMPDIR" |progress "Descomprimiendo ..."
NEW_DIR="$(get_newdir "$TMPDIR")"
[ "$NEW_DIR" ] || die "Error descomprimiendo el fichero"
show_eula "$NEW_DIR/eula.txt" || die "Cancelado por el usuario"
run_wrapper "$NEW_DIR/install" |progress "Instalando ..."
[ $rc -eq 0 ] || die "Error en la instalación"
fix_desktop
end_message
exit 0

